#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Thu Mar 11 15:37:21 2021 from "C:\Users\buggr\Documents\VostroDocuments\PythonExercises\pythonnetwork\PythonNetwork\OMNI_Project\rebTest02.wxg"
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

# I really like this HTML format for a UI
# https://github.com/Akkadius/glass-isc-dhcp
import wx
from RigControl_2 import RigControl
from myRadio import Radio

class MyApp(wx.App):
    def OnInit(self):
        self.frame = RigControl(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.timer = wx.Timer(self.frame)
        self.frame.timer.Start(1000)
        self.frame.Bind(wx.EVT_TIMER, scheduledRun, self.frame.timer)
        self.frame.Show()
        return True

# end of class MyApp

def updatePanel():
    app.frame.vfoA.SetValue(str(rig.vfoA))
    app.frame.vfoB.SetValue(str(rig.vfoB))
    app.frame.select_agc.SetValue( str(rig.agc))
    app.frame.af_level.SetValue( str(rig.volume))



def scheduledRun(e):
    print("DEBUG: %s" % repr(e))
    rig.updateSettings()
    updatePanel()

if __name__ == "__main__":
    rig = Radio(hostname="k8hsq.no-ip.biz", port=50020)

    app = MyApp(0)
    try:
        app.MainLoop()
    except Exception as e:
        print("Fini: %s" % str(e))
    finally:
        pass