#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Thu Mar 11 15:37:21 2021 from "C:\Users\buggr\Documents\VostroDocuments\PythonExercises\pythonnetwork\PythonNetwork\OMNI_Project\rebTest02.wxg"
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from RigControl import RigControl
from example_timer import RepeatedTimer
from myOmni import MyOMNI
from myRadio import Radio
from time import sleep

class MyApp(wx.App):
    def OnInit(self):
        self.frame = RigControl(None, wx.ID_ANY, "")
        # self.frame.text_ctrl_1
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

def updatePanel():
    app.frame.vfoA.SetValue(str(rig.vfoA))
    app.frame.vfoB.SetValue(str(rig.vfoB))
    app.frame.agc_mode.SetValue( str(rig.agc))
    app.frame.af.SetValue( str(rig.volume))



def scheduledRun():
    rig.updateSettings()
    updatePanel()

if __name__ == "__main__":
    rig = Radio(hostname="k8hsq.no-ip.biz", port=50020)
    rt = RepeatedTimer(2, scheduledRun)

    app = MyApp(0)
    try:
        app.MainLoop()
    except Exception as e:
        print("Fini: %s" % str(e))
    finally:
        rt.stop()