# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Mar 10 21:44:00 2021 from "C:\Users\buggr\Documents\VostroDocuments\PythonExercises\pythonnetwork\PythonNetwork\OMNI_Project\rebTest02.wxg"
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((415, 359))
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(30, 30, 30))
        self.SetForegroundColour(wx.Colour(255, 255, 255))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.FlexGridSizer(3, 2, 2, 2)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Value 01")
        label_1.SetBackgroundColour(wx.Colour(50, 50, 204))
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "12345")
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.text_ctrl_1.SetForegroundColour(wx.Colour(255, 255, 255))
        self.text_ctrl_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.text_ctrl_1.SetToolTip("Tool Tip 01")
        sizer_1.Add(self.text_ctrl_1, 1, wx.ALL | wx.EXPAND, 4)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Value 02")
        label_2.SetBackgroundColour(wx.Colour(50, 50, 204))
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER | wx.ALL, 9)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "56789")
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.text_ctrl_2.SetForegroundColour(wx.Colour(255, 255, 255))
        self.text_ctrl_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.text_ctrl_2.SetToolTip("Tool Tip 01")
        sizer_1.Add(self.text_ctrl_2, 2, wx.ALL | wx.EXPAND, 4)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Incr Ctr")
        self.button_1.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_1.Add(self.button_1, 1, wx.ALIGN_CENTER | wx.ALL, 5)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Decr Ctr", style=wx.BU_EXACTFIT)
        self.button_2.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_2.Add(self.button_2, 1, wx.ALL, 5)

        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "Future 1", style=wx.BU_EXACTFIT)
        self.button_3.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_2.Add(self.button_3, 1, wx.ALL, 5)

        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, "Future 2", style=wx.BU_EXACTFIT)
        self.button_4.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_2.Add(self.button_4, 1, wx.ALL, 5)

        self.button_5 = wx.Button(self.panel_1, wx.ID_ANY, "Future 3", style=wx.BU_EXACTFIT)
        self.button_5.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_2.Add(self.button_5, 1, wx.ALL, 5)

        sizer_1.AddGrowableCol(1)
        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_incr_button_1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.on_decr_button_1, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.on_future_button_1, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.on_future_button_2, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.on_future_button_3, self.button_5)
        # end wxGlade

    def on_incr_button_1(self, event):  # wxGlade: MyFrame.<event_handler>
        counter_1 = float(self.text_ctrl_1.GetValue())
        counter_1 = int(counter_1 + 1)
        self.text_ctrl_1.SetValue("%s"%counter_1)
        print("Event handler 'on_incr_button_1'! %s"%counter_1)
        event.Skip()
		
    def on_decr_button_1(self, event):  # wxGlade: MyFrame.<event_handler>
        counter_1 = float(self.text_ctrl_1.GetValue())
        counter_1 = int(counter_1 - 1)
        self.text_ctrl_1.SetValue("%s"%counter_1)
        print("Event handler 'on_decr_button_1'! %s"%counter_1)
        event.Skip()
		

    def on_future_button_1(self, event):  # wxGlade: MyFrame.<event_handler>
        counter_2 = float(self.text_ctrl_2.GetValue())
        counter_2 = int(counter_2 + 1)
        self.text_ctrl_2.SetValue("%s"%counter_2)
        print("Event handler 'on_future_button_1'! %s"%counter_2)
        event.Skip()
        
    def on_future_button_2(self, event):  # wxGlade: MyFrame.<event_handler>
        counter_2 = float(self.text_ctrl_2.GetValue())
        counter_2 = int(counter_2 - 1)
        self.text_ctrl_2.SetValue("%s"%counter_2)
        print("Event handler 'on_future_button_2'! %s"%counter_2)
        event.Skip()
        
    def on_future_button_3(self, event):  # wxGlade: MyFrame.<event_handler>
        self.text_ctrl_1.SetValue("0")
        self.text_ctrl_2.SetValue("0")
        print("Event handler 'on_future_button_3' Reset Counters!")
        event.Skip()
        
# end of class MyFrame
