#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Fri Mar 19 12:02:58 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class RigControl(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RigControl.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        left_control = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(left_control, 1, wx.EXPAND, 0)

        self.xmit_status = wx.RadioBox(self.panel_1, wx.ID_ANY, "Transmit", choices=[""], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.xmit_status.SetToolTip("Transmit")
        self.xmit_status.SetSelection(0)
        left_control.Add(self.xmit_status, 0, 0, 0)

        self.agc_mode = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Slow", "Medium", "Fast", "Off"], style=wx.CB_DROPDOWN)
        left_control.Add(self.agc_mode, 0, 0, 0)

        center_control = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(center_control, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        center_control.Add(sizer_4, 1, wx.EXPAND, 0)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Main Freq"), wx.HORIZONTAL)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)

        self.vfoA = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.vfoA, 0, 0, 0)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Sub Freq"), wx.HORIZONTAL)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)

        self.vfoB = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_6.Add(self.vfoB, 0, 0, 0)

        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        center_control.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.rf = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.rf, 0, 0, 0)

        self.cw_pitch = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.cw_pitch, 0, 0, 0)

        self.af = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.af, 0, 0, 0)

        self.Squelch = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.Squelch, 0, 0, 0)

        right_control = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(right_control, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Something")
        right_control.Add(label_1, 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class RigControl

class MyApp(wx.App):
    def OnInit(self):
        self.frame = RigControl(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
