#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Fri Apr 23 16:52:37 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class RigControl(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RigControl.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1211, 434))
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(106, 106, 106))

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.notebook_1_pane_0 = wx.Panel(self.notebook_1, wx.ID_ANY, style=wx.BORDER_RAISED)
        self.notebook_1.AddPage(self.notebook_1_pane_0, "Main_Panel")

        rigPanel = wx.BoxSizer(wx.VERTICAL)

        top = wx.BoxSizer(wx.HORIZONTAL)
        rigPanel.Add(top, 1, wx.EXPAND, 0)

        top_col2 = wx.GridSizer(3, 1, 0, 0)
        top.Add(top_col2, 1, wx.EXPAND, 0)

        self.vfoA_set = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "VFO A")
        self.vfoA_set.SetMinSize((75, 27))
        self.vfoA_set.SetBackgroundColour(wx.Colour(127, 255, 0))
        self.vfoA_set.Enable(False)
        top_col2.Add(self.vfoA_set, 0, wx.ALL, 9)

        self.vfoB_set = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "VFO B")
        self.vfoB_set.Enable(False)
        top_col2.Add(self.vfoB_set, 0, 0, 0)

        top_col2.Add((0, 0), 0, 0, 0)

        top_col3 = wx.BoxSizer(wx.VERTICAL)
        top.Add(top_col3, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        top_col3.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 1)

        mode = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(mode, 1, wx.EXPAND, 0)

        self.mode_am = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "AM")
        mode.Add(self.mode_am, 0, 0, 0)

        self.mode_usb = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "USB")
        mode.Add(self.mode_usb, 0, 0, 0)

        self.mode_lsb = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "LSB")
        mode.Add(self.mode_lsb, 0, 0, 0)

        self.mode_cw = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "CW")
        mode.Add(self.mode_cw, 0, 0, 0)

        self.mode_fm = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "FM")
        mode.Add(self.mode_fm, 0, 0, 0)

        self.mode_cwr = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "CWR")
        mode.Add(self.mode_cwr, 0, 0, 0)

        self.freq_active_freq = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        self.freq_active_freq.SetMinSize((220, 35))
        self.freq_active_freq.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.freq_active_freq.SetFont(wx.Font(24, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Sans"))
        self.freq_active_freq.SetToolTip("Enter Frequency\nin KHz")
        sizer_3.Add(self.freq_active_freq, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        top_col3.Add(sizer_4, 1, wx.EXPAND, 0)

        self.s_meter_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 20)
        sizer_4.Add(self.s_meter_level, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.freq_standby_freq = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        self.freq_standby_freq.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Sans"))
        sizer_4.Add(self.freq_standby_freq, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        top_col4 = wx.BoxSizer(wx.HORIZONTAL)
        top.Add(top_col4, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(3, 3, 0, 0)
        top_col4.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.button_1 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_1", style=wx.BU_AUTODRAW)
        self.button_1.SetBackgroundColour(wx.Colour(219, 219, 112))
        self.button_1.SetToolTip("This is the Button 1 tooltip")
        grid_sizer_1.Add(self.button_1, 0, wx.ALL | wx.SHAPED, 2)

        self.button_2 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_2", style=wx.BU_AUTODRAW)
        self.button_2.SetBackgroundColour(wx.Colour(127, 255, 0))
        grid_sizer_1.Add(self.button_2, 0, wx.ALL, 3)

        self.button_3 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_3", style=wx.BU_AUTODRAW)
        self.button_3.SetBackgroundColour(wx.Colour(127, 255, 0))
        grid_sizer_1.Add(self.button_3, 0, wx.ALL, 3)

        self.button_4 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_4")
        grid_sizer_1.Add(self.button_4, 0, 0, 0)

        self.button_5 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_5")
        grid_sizer_1.Add(self.button_5, 0, 0, 0)

        self.button_6 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_6")
        grid_sizer_1.Add(self.button_6, 0, 0, 0)

        self.button_7 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_7")
        grid_sizer_1.Add(self.button_7, 0, 0, 0)

        self.button_8 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_8")
        grid_sizer_1.Add(self.button_8, 0, 0, 0)

        self.button_9 = wx.ToggleButton(self.notebook_1_pane_0, wx.ID_ANY, "button_9")
        grid_sizer_1.Add(self.button_9, 0, 0, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        top_col4.Add(sizer_5, 1, wx.EXPAND, 0)

        self.select_mode = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_mode, 0, 0, 0)

        self.select_data_mode = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_data_mode, 0, 0, 0)

        self.select_filter = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_filter, 0, 0, 0)

        self.select_agc = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_agc, 0, 0, 0)

        self.select_att = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_att, 0, 0, 0)

        self.select_preamp = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "")
        sizer_5.Add(self.select_preamp, 0, 0, 0)

        middle = wx.BoxSizer(wx.HORIZONTAL)
        rigPanel.Add(middle, 1, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_0, wx.ID_ANY, "Something nifty goes here later")
        middle.Add(self.text_ctrl_1, 0, wx.ALL | wx.SHAPED, 2)

        bottom = wx.BoxSizer(wx.HORIZONTAL)
        rigPanel.Add(bottom, 1, wx.EXPAND, 0)

        bottom_col1 = wx.BoxSizer(wx.VERTICAL)
        bottom.Add(bottom_col1, 1, wx.EXPAND, 0)

        self.af_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col1.Add(self.af_level, 0, wx.EXPAND, 0)

        self.agc_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col1.Add(self.agc_level, 0, wx.EXPAND, 0)

        self.nr_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col1.Add(self.nr_level, 0, wx.EXPAND, 0)

        self.pbt_low_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col1.Add(self.pbt_low_level, 0, wx.EXPAND, 0)

        bottom_col2 = wx.BoxSizer(wx.VERTICAL)
        bottom.Add(bottom_col2, 1, wx.EXPAND, 0)

        self.rf_gain_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col2.Add(self.rf_gain_level, 0, wx.EXPAND, 0)

        self.rf_power_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col2.Add(self.rf_power_level, 0, wx.EXPAND, 0)

        self.nb_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col2.Add(self.nb_level, 0, wx.EXPAND, 0)

        self.pbt_high_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col2.Add(self.pbt_high_level, 0, wx.EXPAND, 0)

        bottom_col3 = wx.BoxSizer(wx.VERTICAL)
        bottom.Add(bottom_col3, 1, wx.EXPAND | wx.SHAPED, 0)

        self.filter_width = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col3.Add(self.filter_width, 0, wx.EXPAND, 0)

        self.lcd_brightness = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col3.Add(self.lcd_brightness, 0, wx.EXPAND, 0)

        self.nb_depth_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col3.Add(self.nb_depth_level, 0, wx.EXPAND, 0)

        bottom_col4 = wx.BoxSizer(wx.VERTICAL)
        bottom.Add(bottom_col4, 1, wx.EXPAND | wx.SHAPED, 0)

        self.if_shift = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col4.Add(self.if_shift, 0, wx.EXPAND, 0)

        self.notch_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col4.Add(self.notch_level, 0, wx.EXPAND, 0)

        self.nb_width_level = wx.Gauge(self.notebook_1_pane_0, wx.ID_ANY, 10)
        bottom_col4.Add(self.nb_width_level, 0, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        bottom_col4.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.button_10 = wx.Button(self.notebook_1_pane_0, wx.ID_ANY, "button_10")
        self.button_10.SetBackgroundColour(wx.Colour(216, 216, 191))
        grid_sizer_2.Add(self.button_10, 0, wx.ALL, 4)

        self.button_11 = wx.Button(self.notebook_1_pane_0, wx.ID_ANY, "button_11")
        self.button_11.SetBackgroundColour(wx.Colour(216, 216, 191))
        grid_sizer_2.Add(self.button_11, 0, wx.ALL, 4)

        self.button_12 = wx.Button(self.notebook_1_pane_0, wx.ID_ANY, "button_12")
        self.button_12.SetBackgroundColour(wx.Colour(216, 216, 191))
        grid_sizer_2.Add(self.button_12, 0, wx.ALL, 4)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Levels")

        level_panel = wx.BoxSizer(wx.HORIZONTAL)

        meter_levels = wx.BoxSizer(wx.VERTICAL)
        level_panel.Add(meter_levels, 1, wx.EXPAND, 0)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "ALC"), wx.HORIZONTAL)
        meter_levels.Add(sizer_1, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 1)

        self.acl_level = wx.Gauge(self.notebook_1_pane_1, wx.ID_ANY, 10)
        self.acl_level.SetToolTip("ALC")
        sizer_1.Add(self.acl_level, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Power"), wx.HORIZONTAL)
        meter_levels.Add(sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 1)

        self.power_level = wx.Gauge(self.notebook_1_pane_1, wx.ID_ANY, 100)
        self.power_level.SetToolTip("PWR")
        sizer_2.Add(self.power_level, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "SWR"), wx.HORIZONTAL)
        meter_levels.Add(sizer_6, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 1)

        self.swr_level = wx.Gauge(self.notebook_1_pane_1, wx.ID_ANY, 10)
        self.swr_level.SetToolTip("SWR")
        sizer_6.Add(self.swr_level, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        level_panel.Add((400, 20), 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND | wx.RESERVE_SPACE_EVEN_IF_HIDDEN | wx.SHAPED, 0)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, "new tab")

        self.notebook_1_pane_1.SetSizer(level_panel)

        self.notebook_1_pane_0.SetSizer(rigPanel)

        self.Layout()
        # end wxGlade

# end of class RigControl

class MyApp(wx.App):
    def OnInit(self):
        self.frame = RigControl(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
